spring:
  application:
    name: news-system

  datasource:
    url: jdbc:postgresql://localhost:5432/alfred_news
    username: teste
    password: teste
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # cria/atualiza as tabelas automaticamente
    show-sql: true      # mostra o SQL no console, útil pra debug
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080